CREATE DATABASE registration;

CONNECT TO registration;

CREATE TABLE STUDENT (
    "STUD-ID" CHAR(4) NOT NULL PRIMARY KEY,
    "STUD-NAME" CHAR(25),
    "STUD-DOB" CHAR(8),
    "STUD-COURSE" CHAR(15),
    "STUD-INS-DATE" CHAR(15),
    "STUD-UPDT-DATE" CHAR(8)
);